/**
 * PermissionsConsts.java 2008-12-12 下午04:16:54 lgq 版权所有 (c) 2007-2008
 * 江苏鸿信系统集成有限公司
 */

package com.jsict.platform.constants;

/**
 * Generated by PermissionJavaGen.java
 * <p>
 * Description: 包含了权限的常量
 * </p>
 * <p>
 * 数据库: platform@jdbc:oracle:thin:@192.168.1.168:1521:logistic 时间:2009-1-8 12:32:43
 * </p>
 * <p>
 * </p>
 * 
 * @author <a href="mailto: xxx@neusoft.com">作者中文名</a>
 * @version $Revision$
 */
public class PermissionsConsts
{
    
    /**新增交易指令
     
    */
    public static final String ETM_ADD_FUTURES_ORDER = "950046";
    
    /**提交交易指令
     
    */
    public static final String ETM_SUBMIT_FUTURES_ORDER = "950048";
    
    /**暂存交易指令
     
    */
    public static final String ETM_SAVE_FUTURES_ORDER = "950049";
    
    /**新增交易品种分类
     
    */
    public static final String ETM_ADD_CATEGORY = "950050";
    
    /**修改交易品种分类属性
     
    */
    public static final String ETM_EDIT_PROPERTY_FOR_CATEGORY = "950052";
    
    /**编辑交易品种分类
     
    */
    public static final String ETM_EDIT_CATEGORY = "950053";
    
    /**启用交易品种分类
     
    */
    public static final String ETM_ENABLE_CATEGORY = "950054";
    
    /**禁用交易品种分类
     
    */
    public static final String ETM_DISABLE_CATEGORY = "950055";
    
    /**查看所有现货合同
     查看所有的合同，例如管理员可以查看所有用户的合同
    */
    public static final String ETM_SELECT_ALL_CONTRACT_SPOT = "950057";
    
    /**查看交易设置
     
    */
    public static final String ETM_VIEW_SETTING = "950058";
    
    /**编辑交易设置
     
    */
    public static final String ETM_EDIT_SETTING = "950059";
    
    /**可审核
     显示管理员审核现货订单的那个tab.
    */
    public static final String ETM_CAN_AUDIT_SPOT = "950060";
    
    /**重置交易设置
     
    */
    public static final String ETM_RESET_SETTING = "950061";
    
    /**现货挂单
     可以挂单
    */
    public static final String ETM_CAN_QUOTE_SPOT = "950062";
    
    /**显示挂单信息
     
    */
    public static final String ETM_DISPLAY_QUOTATION = "950063";
    
    /**显示撤牌信息
     
    */
    public static final String ETM_DISPLAY_CANCELED_INFO = "950064";
    
    /**显示退牌信息
     
    */
    public static final String ETM_DISPLAY_QUIT_INFO = "950065";
    
    /**显示驳回信息
     
    */
    public static final String ETM_DISPLAY_REJECT_INFO = "950066";
    
    /**显示待挂单信息
     
    */
    public static final String ETM_DISPLAY_WAITING_QUOTE_INFO = "950067";
    
    /**显示待审核信息
     
    */
    public static final String ETM_DISPLAY_WAITING_AUDIT_INFO = "950068";
    
    /**可撤牌
     
    */
    public static final String ETM_CAN_CANCEL_SPOT = "950069";
    
    /**现货市场控制
     
    */
    public static final String ETM_SPOT_CTRL = "950070";
    
    /**远期现货市场控制
     
    */
    public static final String ETM_FUTURES_CTRL = "950071";
    
    /**可修改
     
    */
    public static final String ETM_CAN_MODIFY_SPOT = "950072";
    
    /**可查看
     
    */
    public static final String ETM_CAN_VIEW_SPOT = "950073";
    
    /**查看交易日
     
    */
    public static final String ETM_VIEW_TRADEDATE = "950074";
    
    /**编辑交易日
     
    */
    public static final String ETM_EDIT_TRADE_DATE = "950075";
    
    /**查看所有远期合同
     
    */
    public static final String ETM_SELECT_ALL_CONTRACT_FUTURES = "950076";
    
    /**可查看交易商
     
    */
    public static final String ETM_CAN_VIEW_PARTICIPANT = "950077";
    
    /**查看席位列表
     
    */
    public static final String ETM_CAN_VIEW_TRADESEAT_LIST = "950078";
    
    /**可编辑交易商
     
    */
    public static final String ETM_CAN_EDIT_PARTICIPANT = "950079";
    
    /**可注销交易商
     
    */
    public static final String ETM_CAN_DELETE_PARTICIPANT = "950080";
    
    /**可查看交易席位
     
    */
    public static final String ETM_CAN_VIEW_TRADESEAT = "950081";
    
    /**可编辑交易席位
     
    */
    public static final String ETM_CAN_EDIT_TRADESEAT = "950082";
    
    /**可注销交易席位
     
    */
    public static final String ETM_CAN_DELETE_TRADESEAT = "950083";
    
    /**可新建交易席位
     
    */
    public static final String ETM_CAN_NEW_TRADESEAT = "950084";
    
    /**可操作账户资金
     
    */
    public static final String ETM_CAN_COORDINATE_TRADEACCOUNT = "950085";
    
    /**可禁止出入金
     
    */
    public static final String ETM_CAN_COMMAND_FORBID_CASH = "950086";
    
    /**可新建转账申请
     
    */
    public static final String ETM_CAN_NEW_TRANSFER_RECORD = "950087";
    
    /**可审核转帐申请
     
    */
    public static final String ETM_CAN_AUDIT_TRANSFER_RECORD = "950088";
    
    /**可查看所有席位资金流向
     
    */
    public static final String ETM_CAN_VIEW_ALL_CASHFLOW = "950089";
    
    /**可禁用交易席位
     
    */
    public static final String ETM_CAN_FORBID_TRADESEAT = "950090";
    
    /**编辑品种
     
    */
    public static final String ETM_EDIT_GOODS_TYPE = "950092";
    
    /**新建品种
     
    */
    public static final String ETM_ADD_GOODS_TYPE = "950093";
    
    /**启用品种
     
    */
    public static final String ETM_ENABLE_GOODS_TYPE = "950094";
    
    /**禁用品种
     
    */
    public static final String ETM_DISABLE_GOODS_TYPE = "950095";
    
    /**指定交易品种默认值
     
    */
    public static final String ETM_ASSIGN_DEFAULT_VALUE = "950096";
    
    /**发布远期交易品种
     
    */
    public static final String ETM_PUBLISH_FUTURES_GOODS_TYPE = "950097";
    
    /**启用远期交易品种
     
    */
    public static final String ETM_ENABLE_FUTURES_GOODS_TYPE = "950098";
    
    /**禁用远期交易品种
     
    */
    public static final String ETM_DISABLE_FUTURES_GOODS_TYPE = "950099";
    
    /**查看远期合同正文
     
    */
    public static final String ETM_VIEW_FUTURES_CONTRACT_TEXT = "950100";
    
    /**合同违约处理
     
    */
    public static final String ETM_VIOLATE_CONTRACT = "950101";
    
    /**远期交易评价
     
    */
    public static final String ETM_EVALUATE_FUTURES_TRADE = "950102";
    
    /**提前交收申请
     
    */
    public static final String ETM_ADVANCED_DELIVERY_APPLY = "950103";
    
    /**撤销交收申请
     
    */
    public static final String ETM_WITHDRAW_DELIVERY_APPLY = "950104";
    
    /**查看交收状态
     
    */
    public static final String ETM_VIEW_FUTURES_DELIVERY_RECORD = "950105";
    
    /**查看现货合同正文
     
    */
    public static final String ETM_VIEW_SPOT_CONTRACT_TEXT = "950106";
    
    /**查看现货交收状态
     
    */
    public static final String ETM_VIEW_SPOT_DELIVERY_RECORD = "950107";
    
    /**现货交易评价
     
    */
    public static final String ETM_EVALUATE_SPOT_TRADE = "950108";
    
    /**可新建交易商
     
    */
    public static final String ETM_CAN_NEW_PARTICIPANT = "950109";
    
    /**查看所有日结算报表
     查看所有日期的日结算报表，可以选择日期
    */
    public static final String ETM_SELECT_ALL_DAILY_BALANCE = "950110";
    
    /**可新建生产厂商
     
    */
    public static final String ETM_CAN_NEW_MANUFACTURER = "950112";
    
    /**可修改生产厂商
     
    */
    public static final String ETM_CAN_EDIT_MANUFACTURER = "950113";
    
    /**可注销生产厂商
     
    */
    public static final String ETM_CAN_DELETE_MANUFACTURER = "950114";
    
    /**可新建交收仓库
     
    */
    public static final String ETM_CAN_NEW_WAREHOUSE = "950115";
    
    /**可修改交收仓库
     
    */
    public static final String ETM_CAN_EDIT_WAREHOUSE = "950116";
    
    /**可注销交收仓库
     
    */
    public static final String ETM_CAN_DELETE_WAREHOUSE = "950117";
    
    /**撤销交易指令
     
    */
    public static final String ETM_WITHDRAW_FUTURES_ORDER = "950118";
    
    /**查看交易指令
     
    */
    public static final String ETM_VIEW_FUTURES_ORDER = "950119";
    
    /**匹配合同
     
    */
    public static final String ETM_MATCH_CONTRACT = "950120";
    
    /**申请调解
     
    */
    public static final String ETM_CAN_ADD_INTERCESSION_APPLY = "950121";
    
    /**编辑调解申请
     
    */
    public static final String ETM_CAN_EDIT_INTERCESSION_APPLY = "950122";
    
    /**取回申请
     
    */
    public static final String ETM_CAN_TAKEBACK_INTERCESSION_APPLY = "950123";
    
    /**审核调解
     
    */
    public static final String ETM_CAN_AUDIT_INTERCESSION_APPLY = "950124";
    
    /**可更新
     
    */
    public static final String ETM_CAN_UPDATE_WAREHOUSE_RECEIPT = "950125";
    
    /**可注销
     
    */
    public static final String ETM_CAN_NULLIFY_WAREHOUSE_RECEIPT = "950126";
    
    /**可审核
     
    */
    public static final String ETM_CAN_AUDIT_WAREHOUSE_RECEIPT = "950127";
    
    /**可驳回
     
    */
    public static final String ETM_CAN_REFUSE_WAREHOUSE_RECEIPT = "950128";
    
    /**可冻结
     
    */
    public static final String ETM_CAN_FREEZE_WAREHOUSE_RECEIPT = "950129";
    
    /**可解冻
     
    */
    public static final String ETM_CAN_ICEOUT_WAREHOUSE_RECEIPT = "950130";
    
    /**可恢复
     
    */
    public static final String ETM_CAN_RECOVER_WAREHOUSE_RECEIPT = "950131";
    
    /**重新提交申请
     
    */
    public static final String ETM_CAN_RESUME_INTERCESSION_APPLY = "950132";
    
    /**可查看
     
    */
    public static final String ETM_CAN_VIEW_WAREHOUSE_RECEIPT = "950133";
    
    /**电子交易用户
     EtmUser
    */
    public static final String PLF_ETMUSER = "990001";
    
    /**物流配载用户
     LcaUser
    */
    public static final String PLF_LCAUSER = "990002";
    
    /**仓储用户
     WmsUser
    */
    public static final String PLF_WMSUSER = "990003";
    
    /**公共平台用户
     PlfUser
    */
    public static final String PLF_PLFUSER = "990004";
    
    /**门户平台用户
     PtlUser
    */
    public static final String PLF_PTLUSER = "990005";
    
    /**修改用户权限
     Edit UserAccount
    */
    public static final String PLF_EDITUSER = "990017";
    

}
