/**
 * RolesConsts.java 2008-12-12 下午04:16:54 lgq 版权所有 (c) 2007-2008
 * 江苏鸿信系统集成有限公司
 */

package com.jsict.platform.constants;

/**
 * Generated by PermissionJavaGen.java
 * <p>
 * Description: 包含了权限的常量
 * </p>
 * <p>
 * 数据库: platform@jdbc:oracle:thin:@192.168.1.168:1521:logistic 时间:2009-1-8 12:32:43
 * </p>
 * <p>
 * </p>
 * 
 * @author <a href="mailto: xxx@neusoft.com">作者中文名</a>
 * @version $Revision$
 */
public class RolesConsts
{
    /**Admin
    	管理员
    	Admin
    */
    public static final String ROLE_ADMIN = "Admin";
  	
    /**Guest
    	访客
    	Guest
    */
    public static final String ROLE_GUEST = "Guest";
  	
    /**LcaOperator
    	物流运营商
    	物流系统运营商
    */
    public static final String ROLE_LCAOPERATOR = "LcaOperator";
  	
    /**LcaCarrier
    	物流承运商
    	物流承运商
    */
    public static final String ROLE_LCACARRIER = "LcaCarrier";
  	
    /**LcaClient
    	物流合同客户
    	物流合同客户
    */
    public static final String ROLE_LCACLIENT = "LcaClient";
  	
    /**WmsProviderFinance
    	运营商(财务)
    	仓储平台运营商，管理财务
    */
    public static final String ROLE_WMSPROVIDERFINANCE = "WmsProviderFinance";
  	
    /**WmsAdmin
    	仓储管理员
    	仓储平台管理员
    */
    public static final String ROLE_WMSADMIN = "WmsAdmin";
  	
    /**WmsProviderBaseinfo
    	运营商(资料)
    	仓储平台管理员，负责基本资料维护
    */
    public static final String ROLE_WMSPROVIDERBASEINFO = "WmsProviderBaseinfo";
  	
    /**WmsProviderWarehouse
    	运营商(仓库)
    	仓储平台运营商，负责出入库相关事宜
    */
    public static final String ROLE_WMSPROVIDERWAREHOUSE = "WmsProviderWarehouse";
  	
    /**WmsClient
    	仓储客户
    	仓储平台客户
    */
    public static final String ROLE_WMSCLIENT = "WmsClient";
  	
    /**TEST
    	测试角色
    	
    */
    public static final String ROLE_TEST = "TEST";
  	
    /**ptl_user
    	门户用户
    	
    */
    public static final String ROLE_PTL_USER = "ptl_user";
  	
    /**business
    	ETM-交易商
    	etm的交易商们
    */
    public static final String ROLE_BUSINESS = "business";
  	
    /**ETM-PROVIDER
    	ETM运营商
    	
    */
    public static final String ROLE_ETM_PROVIDER = "ETM-PROVIDER";
  	
    

}
