/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.itcast.bbs.web.struts.forms;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.upload.FormFile;

import cn.itcast.bbs.entities.Sex;
import cn.itcast.bbs.utils.PatternUtils;
import cn.itcast.bbs.web.struts.forms.base.BaseActionForm;
import cn.itcast.bbs.web.struts.utils.ActionFormDate;

/**
 * @author 传智播客.汤阳光 Jun 26, 2008
 */
@SuppressWarnings("serial")
public class UserForm extends BaseActionForm {
	// --- 基本信息
	private String loginName;// 登录名
	private String password;// 密码
	private String password2;// 密码2
	private String email;// Email地址

	// --- 个人信息
	private String nickname;// 昵称
	private Sex sex = Sex.SECRECY;// 性别, 默认为保密
	private ActionFormDate birthday;// 生日
	private FormFile avatarFile;// 头像
	private String qq;
	private String msn;
	private String comeFrom;// 来自哪里
	private String signature;// 签名
	
	private String realname;	//真实姓名
	private String cellphone;	//常用手机	
	private String major;		//浙大毕业专业
	private String graduyear;	//毕业年份
	private String number;		//毕业证号
	private String education;	//学历
	private String title;		//职称
	private String birthplace;	//籍贯
	private String address;		//居住地址
	private String postcode;	//邮编
	private String marriage;	//婚姻状况
	private String car;			//常用交通工具
	private String speciality;	//本人特长
	private String resource;	//能为校友提供的资源
	private String advice;		//意见与建议
	private String activitypoint;//热心度
	private String memberid;//会员ID

	private boolean autoLogin;
	private int autoLoginDays;

	private int[] groupIds;

	public ActionErrors validateRegister(ActionMapping mapping, HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();

		if (StringUtils.isBlank(loginName) || loginName.length() > 64) {
			errors.add("loginName", new ActionMessage("请输入用户名, 长度不能超过64个字符", false));
		}
		if (StringUtils.isBlank(nickname) || loginName.length() > 64) {
			errors.add("nickname", new ActionMessage("请输入昵称, 长度不能超过64个字符", false));
		}
		if (StringUtils.isBlank(realname) || realname.length() > 64) {
			errors.add("realname", new ActionMessage("请输入真实姓名, 长度不能超过64个字符", false));
		}
		if (StringUtils.isBlank(cellphone) || cellphone.length() > 64) {
			errors.add("cellphone", new ActionMessage("请输入常用手机, 长度不能超过64个字符", false));
		}
		if (StringUtils.isBlank(major) || major.length() > 64) {
			errors.add("major", new ActionMessage("请输入毕业专业, 长度不能超过64个字符", false));
		}
		if (StringUtils.isBlank(education) || education.length() > 64) {
			errors.add("education", new ActionMessage("请输入学历, 长度不能超过64个字符", false));
		}
		if (StringUtils.isBlank(title) || title.length() > 64) {
			errors.add("title", new ActionMessage("请输入现在职称, 长度不能超过64个字符", false));
		}
		if (StringUtils.isBlank(birthplace) || birthplace.length() > 128) {
			errors.add("birthplace", new ActionMessage("请输入籍贯, 长度不能超过128个字符", false));
		}
		if (StringUtils.isBlank(address) || address.length() > 128) {
			errors.add("address", new ActionMessage("请输入居住地址, 长度不能超过128个字符", false));
		}
		if (StringUtils.isBlank(postcode) || postcode.length() > 128) {
			errors.add("postcode", new ActionMessage("请输入邮编, 长度不能超过128个字符", false));
		}
		if (StringUtils.isBlank(comeFrom) || comeFrom.length() > 128) {
			errors.add("comeFrom", new ActionMessage("请输入所在单位, 长度不能超过128个字符", false));
		}
		if (!PatternUtils.isEmail(email)) {
			errors.add("email", new ActionMessage("请输入正确的email地址", false));
		}

		if (StringUtils.isEmpty(password)) {
			errors.add("password", new ActionMessage("请输入密码", false));
		} else if (!password.equals(password2)) {
			errors.add("password2", new ActionMessage("请确认密码", false));
		}

		if (signature != null && signature.length() > 500) {
			errors.add("password", new ActionMessage("签名的长度不能超过500个字符", false));
		}

		return errors;
	}

	public ActionErrors validateEdit(ActionMapping mapping, HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		if (StringUtils.isBlank(nickname) || loginName.length() > 64) {
			errors.add("nickname", new ActionMessage("请输入昵称, 长度不能超过64个字符", false));
		}
		if (!PatternUtils.isEmail(email)) {
			errors.add("email", new ActionMessage("请输入正确的email地址", false));
		}

		if (signature != null && signature.length() > 500) {
			errors.add("password", new ActionMessage("签名的长度不能超过500个字符", false));
		}

		return errors;
	}

	public ActionErrors validateChangePassword(ActionMapping mapping, HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		if (StringUtils.isEmpty(password)) {
			errors.add("password", new ActionMessage("请输入密码", false));
		} else if (!password.equals(password2)) {
			errors.add("password2", new ActionMessage("请确认密码", false));
		}

		return errors;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPassword2() {
		return password2;
	}

	public void setPassword2(String password2) {
		this.password2 = password2;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Sex getSex() {
		return sex;
	}

	public void setSex(Sex sex) {
		this.sex = sex;
	}

	public ActionFormDate getBirthday() {
		return birthday;
	}

	public void setBirthday(ActionFormDate birthday) {
		this.birthday = birthday;
	}

	public FormFile getAvatarFile() {
		return avatarFile;
	}

	public void setAvatarFile(FormFile avatarFile) {
		this.avatarFile = avatarFile;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getMsn() {
		return msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	public String getComeFrom() {
		return comeFrom;
	}

	public void setComeFrom(String comeFrom) {
		this.comeFrom = comeFrom;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public boolean isAutoLogin() {
		return autoLogin;
	}

	public void setAutoLogin(boolean autoLogin) {
		this.autoLogin = autoLogin;
	}

	public int getAutoLoginDays() {
		return autoLoginDays;
	}

	public void setAutoLoginDays(int autoLoginDays) {
		this.autoLoginDays = autoLoginDays;
	}

	public int[] getGroupIds() {
		return groupIds;
	}

	public void setGroupIds(int[] groupIds) {
		this.groupIds = groupIds;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getCellphone() {
		return cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getMajor() {
		return major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getGraduyear() {
		return graduyear;
	}

	public void setGraduyear(String graduyear) {
		this.graduyear = graduyear;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getEducation() {
		return education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getBirthplace() {
		return birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getMarriage() {
		return marriage;
	}

	public void setMarriage(String marriage) {
		this.marriage = marriage;
	}

	public String getCar() {
		return car;
	}

	public void setCar(String car) {
		this.car = car;
	}

	public String getSpeciality() {
		return speciality;
	}

	public void setSpeciality(String speciality) {
		this.speciality = speciality;
	}

	public String getResource() {
		return resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}

	public String getAdvice() {
		return advice;
	}

	public void setAdvice(String advice) {
		this.advice = advice;
	}

	public String getActivitypoint() {
		return activitypoint;
	}

	public void setActivitypoint(String activitypoint) {
		this.activitypoint = activitypoint;
	}

	public String getMemberid() {
		return memberid;
	}

	public void setMemberid(String memberid) {
		this.memberid = memberid;
	}

}
